
variables:
  GIT_SUBMODULE_STRATEGY: recursive

.test:
  before_script:
    - mkdir build
    - cd build
  script:
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --config Debug
    - ctest --build-config Debug --output-on-failure

windows:
  before_script:
    - choco install -y winflexbison3
  extends: .test
  tags:
    - windows

linux:
  before_script:
    - apt-get update
    - apt-get install -y flex
  extends: .test
  tags:
    - docker
  image: rikorose/gcc-cmake
