
variables:
  GIT_SUBMODULE_STRATEGY: recursive

.test:
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --config Debug
    - ctest --build-config Debug --output-on-failure

windows:
  before_script:
    - choco install wget
    - wget "https://github.com/lexxmark/winflexbison/releases/download/v2.5.23/win_flex_bison-2.5.23.zip"
    - tar -xf win_flex_bison-2.5.23.zip 
    - set PATH=%PATH%;%CD%

  extends: .test
  tags:
    - windows

linux:
  before_script:
    - apt-get update
    - apt-get install -y flex
  extends: .test
  tags:
    - docker
  image: rikorose/gcc-cmake
